server:
  host: localhost
  port: 9002
  schema:
    http: http
    ws: ws

client:
  host: localhost:9002
agent:
  host: localhost:9002

version:
  agent: 1.0.0
  server: 1.0.0
  client: 1.0.0

helpUrl: https://github.com/logerror/easylog/blob/master/README.md