server:
  port: 9002

oem:
  name: "Terminal 2 Terminal"

helpUrl: https://github.com/logerror/easylog/blob/master/README.md

auth:
  mode: local
  users:
    - username: "admin"
      password: "admin123"